### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils

### ISSUE THREAD

**Issue by rajadain** [rajadain/trelliscope#1]
```
[ERROR] [SECURITY][10/05/2017 04:53:05.295] [WebServer-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemImpl(WebServer)] Uncaught error from thread [WebServer-akka.actor.default-dispatcher-3]: org/apache/commons/io/IOUtils, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[WebServer]
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
  at geotrellis.spark.io.s3.S3CollectionReader$$anonfun$read$1.apply(S3CollectionReader.scala:58)
  at geotrellis.spark.io.s3.S3CollectionReader$$anonfun$read$1.apply(S3CollectionReader.scala:56)
  at geotrellis.spark.io.LayerReader$$anonfun$3$$anonfun$apply$1.apply(LayerReader.scala:81)
  at geotrellis.spark.io.LayerReader$$anonfun$3$$anonfun$apply$1.apply(LayerReader.scala:81)
  at scalaz.concurrent.Task$.Try(Task.scala:457)
  at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:354)
  at scalaz.concurrent.Task$$anonfun$apply$25.apply(Task.scala:354)
  at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
  at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 13 more
```

**Comment by rajadain** [comment]
Test request:

```bash
http :7316/query shape='{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-75.097046,40.048643],[-75.201416,39.972911],[-75.080566,39.88445],[-74.998169,39.993956],[-75.097046,40.048643]]]}}"' \
                 layer="climatology-ppt-01-epsg5070" \
                 bucket=$BUCKET \
                 awsAccessKeyId=$AWS_ACCESS_KEY_ID \
                 awsSecretAccessKey=$AWS_SECRET_ACCESS_KEY
```

**Comment by rajadain** [comment]
Fixed by including Spark in the build: https://github.com/rajadain/trelliscope/commit/fb34696b7d3f3525c7d59bc16af36d76b437477e

The `provided` keyword indicates that there is a dependency, but it will be provided by the environment so SBT was not downloading it. By removing it, we ensure that SBT does download and include Spark.
